version: '3.8'
services:
  web:
    build:
      context: . # The directory to use as the build context
      dockerfile: Dockerfile
    platform: linux/amd64 # Specify the target platform
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/code # Mounts your local code to the container for development
    command: ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]
